name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    env:
      IMAGE_TAG: patrickmcdonald/openapi-demo:${{ github.run_number }}
    steps:
    - uses: actions/checkout@v4
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Build the Docker image
      run: docker build . --file src/OpenApi/Dockerfile --tag $IMAGE_TAG
    - name: Push the Docker image
      run: docker push $IMAGE_TAG
      env:
        DOCKER_BUILDKIT: 1
        IMAGE_TAG: ${{ env.IMAGE_TAG }}
