name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  IMAGE_TAG: patrickmcdonald/openapi-demo:${{ github.run_number }}

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build the Docker image
      run: docker build . --file src/OpenApi/Dockerfile --tag $IMAGE_TAG

    - name: Push the Docker image
      run: docker push $IMAGE_TAG
      env:
        DOCKER_BUILDKIT: 1
        IMAGE_TAG: ${{ env.IMAGE_TAG }}

  deploy-to-azure:
    runs-on: ubuntu-latest
    needs: build-and-push
    permissions:
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.DEMOOPENAPICONTAINER_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.DEMOOPENAPICONTAINER_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.DEMOOPENAPICONTAINER_AZURE_SUBSCRIPTION_ID }}

      - name: Deploy to Azure Container App
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }}
          registryUrl: hub.docker.com
          registryUsername: ${{ secrets.DOCKERHUB_USERNAME }}
          registryPassword: ${{ secrets.DOCKERHUB_TOKEN }}
          containerAppName: demo-openapi-container
          resourceGroup: azure-demos
          imageToDeploy: hub.docker.com/repository/docker/${{ env.IMAGE_TAG }}
