name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    outputs:
      image_tag: ${{ steps.set_tag.outputs.image_tag }}
    steps:
    - uses: actions/checkout@v4
    - name: Set Docker image tag
      id: set_tag
      run: echo "image_tag=openapi-demo:${GITHUB_RUN_NUMBER}" >> $GITHUB_OUTPUT
    - name: Build the Docker image
      run: docker build . --file src/OpenApi/Dockerfile --tag ${{ steps.set_tag.outputs.image_tag }}

  publish:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - uses: actions/checkout@v4
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Pull the Docker image
      run: docker pull ${{ needs.build.outputs.image_tag }} || true
    - name: Push the Docker image
      run: docker push ${{ needs.build.outputs.image_tag }}
      env:
        DOCKER_BUILDKIT: 1
