name: Trigger auto deployment for openapi

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - '**'
    - '.github/workflows/openapi-AutoDeployTrigger-d86d613b-6ad6-4310-b6e9-d5380fb6cf01.yml'

  # Allow manual trigger 
  workflow_dispatch:      

env:
  IMAGE_TAG: patrickmcdonald/openapi:${{ github.sha }}

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.OPENAPI_REGISTRY_USERNAME }}
        password: ${{ secrets.OPENAPI_REGISTRY_PASSWORD }}

    - name: Build the Docker image
      run: docker build . --file src/OpenApi/Dockerfile --tag $IMAGE_TAG

    - name: Push the Docker image
      run: docker push $IMAGE_TAG
      env:
        DOCKER_BUILDKIT: 1
        IMAGE_TAG: ${{ env.IMAGE_TAG }}

  deploy-to-azure:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.OPENAPI_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.OPENAPI_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.OPENAPI_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          registryUrl: docker.io
          containerAppName: openapi
          resourceGroup: rg-OpenApiExamples
          imageToDeploy: ${{ env.IMAGE_TAG }}
