@OpenApi_HostAddress = https://localhost:7157

GET {{OpenApi_HostAddress}}/customers/
Accept: application/json

###

@id=1
GET {{OpenApi_HostAddress}}/customers/{{id}}

###

POST {{OpenApi_HostAddress}}/customers/
Content-Type: application/json
Accept: application/json

{
  "name": "Jim Davis"
}

###

GET {{OpenApi_HostAddress}}/customers/error
